# Generated by Django 5.2.8 on 2025-11-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
    ]
